# Generated by Django 3.0.6 on 2020-05-04 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weblink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('originalurl', models.URLField(max_length=250)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('visits', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
