# Generated by Django 3.0.7 on 2020-06-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_default.jpg', upload_to='_profile_pics'),
        ),
    ]
