# Generated by Django 3.0.5 on 2020-05-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
