# Generated by Django 3.0.5 on 2020-04-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200427_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='posted_date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
