# Generated by Django 3.0.6 on 2020-05-12 03:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book_status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('book_status', models.BooleanField(default=False)),
                ('checked_in', models.DateField(default=django.utils.timezone.now)),
                ('checked_out', models.DateField(default=django.utils.timezone.now)),
                ('availability', models.TextField()),
            ],
            options={
                'ordering': ['checked_out'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('book_summary', models.TextField()),
                ('author', models.ManyToManyField(to='libraryapp.Author')),
                ('category', models.ManyToManyField(to='libraryapp.Category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
