# Generated by Django 3.0.6 on 2020-05-05 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(unique=True)),
                ('short_url', models.URLField(unique=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
    ]
