# Generated by Django 3.0.6 on 2020-05-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorten',
            name='id',
        ),
        migrations.AlterField(
            model_name='shorten',
            name='original_url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='shorten',
            name='short_url',
            field=models.SlugField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
