# Generated by Django 3.0.6 on 2020-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortenapp', '0002_auto_20200505_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorten',
            name='original_url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
